### ISSUE TITLE
[Question] What role does `fake_node_id`  play?

### ISSUE THREAD

**Issue by ytgui** [whtsky/maga#7]
Hi,
I am studying on this project to understand `dht` protocol, but I found this method `fake_node_id` in [https://github.com/whtsky/maga/blob/master/maga.py#L196](https://github.com/whtsky/maga/blob/master/maga.py#L196) is really obscure, could you tell me about this?
Thank you

**Comment by itdaniher** [comment]
IIRC, It generates a guess for a infohash/peer, both being the same shape bytestring.

http://www.bittorrent.org/beps/bep_0005.html

**Comment by ytgui** [comment]
@itdaniher thanks a lot, issue closed
